#!/usr/bin/env node
// Reads frontend/.env (gitignored — a per-developer PrimeUI Community
// License key, never committed) and writes the gitignored TS file
// app.config.ts imports it from. Angular's build has no native .env
// support: `angular.json`'s `define` takes a literal string, not an
// environment lookup, so this is the plain, dependency-free equivalent —
// one KEY=VALUE line does not need a real dotenv parser.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontendRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = join(frontendRoot, '.env');
const outPath = join(frontendRoot, 'src/app/core/env.generated.ts');

function readLicenseKey() {
  if (!existsSync(envPath)) {
    return '';
  }
  const line = readFileSync(envPath, 'utf8')
    .split('\n')
    .find((entry) => entry.startsWith('PRIMENG_LICENSE_KEY='));
  return line ? line.slice('PRIMENG_LICENSE_KEY='.length).trim() : '';
}

const licenseKey = readLicenseKey();
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// Generated by scripts/generate-env.mjs from .env — do not edit, do not commit.\n` +
    `export const PRIMENG_LICENSE_KEY = '${licenseKey}';\n`,
);
